[package]
name = "rustgi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustgi"
crate-type = ["cdylib", "rlib"]

[dependencies]
http = "0.2.9"
hyper = { version = "1.0.0-rc.3", features = ["server", "http1"] }
lazy_static = "1.4.0"
pyo3 = "0.19.0"
pyo3-log = { version = "0.8.1", optional = true }
log = { version = "0.4.17", optional = true }
tokio = { version = "1.28.0", features = ["macros", "net", "signal", "rt", "rt-multi-thread"] , optional = true }
event-listener = "2.5.3"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { version = "0.5", features = ["disable_initial_exec_tls"], optional = true }

[dev-dependencies]
rustgi = { path = ".", features = ["python"] }

[features]
python = ["dep:tokio", "dep:jemallocator", "pyo3/extension-module", "dep:log", "dep:pyo3-log"]

[profile.release]
lto = true
opt-level = 3
strip = true
debug = false
codegen-units = 1
