[package]
name = "rustgi"
version = "0.1.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustgi"
crate-type = ["cdylib", "rlib"]

[dependencies]
http = "0.2.9"
lazy_static = "1.4.0"
pyo3 = "0.19.0"
pyo3-log = { version = "0.8.1"}
log = { version = "0.4.17" }
bytes = "1.4.0"
http-body = "1.0.0"
llhttp_rs = { git = "https://github.com/TcMits/llhttp-rs.git", version = "0.1.0" }
rustls = "0.21.6"
rustls-pemfile = "1.0.3"
tokio = { version = "1.32.0", features = ["net", "signal", "rt", "macros", "io-util"] }
tokio-rustls = "0.24.1"

[dev-dependencies]
rustgi = { path = ".", features = ["python"] }

[features]
python = ["pyo3/extension-module"]

[profile.release]
lto = true
opt-level = 3
strip = true
codegen-units = 1
debug = false

[profile.dev]
debug = true
